/**
 * Omni sprite geometry — pure maths, no DOM, no Svelte.
 *
 * The world art lives in `static/world/omni/{omni-0.png,atlas.json}`: a 1024x1024
 * packer page with 190 frames (7 animations x 5 real directions, 48x64, pivot
 * 24,60). That sheet cannot drive a CSS `steps()` animation directly, because a
 * `background-position-x` walk needs the frames of one animation to be contiguous
 * on a single row and two of them (`omni/wave/S`, `omni/work/S`) wrap to the next
 * packer row. Downloading a 408 KB page to show a 36 px avatar in the rail would
 * also be wasteful.
 *
 * So the S-facing frames of the five poses the avatar uses are repacked, offline,
 * into one contiguous 1248x64 strip: `static/omni/poses/omni-strip.png` (13964
 * bytes). Frame n sits at exactly `n * frameW`, which makes the whole animation a
 * single CSS declaration and zero JavaScript per frame.
 *
 * The strip and the `OMNI_STRIP` descriptor below are generated from `atlas.json`
 * by `build-strip.py` (kept in the agent scratchpad, not in the repo — only its
 * output is committed). `stripFromAtlas` reimplements that same derivation here so
 * the unit test can recompute the descriptor from the real `atlas.json` and fail
 * if the art is ever repacked without regenerating the strip.
 */

/** Moods emitted by `omni://intent` (`Mood` in `core/omni/intent.rs`). */
export type Mood =
  | "neutral"
  | "happy"
  | "curious"
  | "proud"
  | "worried"
  | "sleepy"
  | "focused";

export const MOODS: readonly Mood[] = [
  "neutral",
  "happy",
  "curious",
  "proud",
  "worried",
  "sleepy",
  "focused",
];

/** Poses present in the repacked strip, in strip order. */
export type OmniPose = "idle" | "talk" | "wave" | "sleep" | "work";

export const STRIP_POSES: readonly OmniPose[] = ["idle", "talk", "wave", "sleep", "work"];

/** Direction repacked into the strip: S, the one that faces the viewer. */
export const STRIP_DIRECTION = "S";

export interface PoseSlice {
  /** Index of the pose's first frame inside the strip. */
  start: number;
  count: number;
  fps: number;
  loop: boolean;
}

export interface SpriteStrip {
  /** Absolute URL under `static/`. */
  image: string;
  frameW: number;
  frameH: number;
  /** Total frames in the strip (all poses). */
  frames: number;
  poses: Record<OmniPose, PoseSlice>;
}

/** Generated by `build-strip.py` from `static/world/omni/atlas.json`. */
export const OMNI_STRIP: SpriteStrip = {
  image: "/omni/poses/omni-strip.png",
  frameW: 48,
  frameH: 64,
  frames: 26,
  poses: {
    idle: { start: 0, count: 4, fps: 6, loop: true },
    talk: { start: 4, count: 4, fps: 8, loop: true },
    wave: { start: 8, count: 6, fps: 10, loop: true },
    sleep: { start: 14, count: 4, fps: 4, loop: true },
    work: { start: 18, count: 8, fps: 10, loop: true },
  },
};

/**
 * Mood -> pose. `speaking` wins over the mood: an agent that is streaming text
 * talks, and a sleeping Omni that starts talking wakes up.
 */
export function moodPose(mood: Mood | string | null | undefined, speaking = false): OmniPose {
  if (speaking) return "talk";
  switch (mood) {
    case "happy":
    case "proud":
      return "wave";
    case "sleepy":
      return "sleep";
    case "focused":
      return "work";
    case "curious":
    case "worried":
    case "neutral":
      return "idle";
    default:
      // Unknown mood (older backend, malformed intent) behaves like neutral.
      return "idle";
  }
}

/** The slice of a pose, falling back to `idle` for anything unknown. */
export function poseSlice(strip: SpriteStrip, pose: OmniPose | string): PoseSlice {
  return strip.poses[pose as OmniPose] ?? strip.poses.idle;
}

/**
 * `background-position-x` for one frame of a pose, in CSS pixels (negative, since
 * the strip scrolls leftwards behind the 48x64 window). `index` is clamped into
 * the pose, so callers cannot scroll into the neighbouring pose.
 */
export function framePositionPx(
  strip: SpriteStrip,
  pose: OmniPose | string,
  index: number,
): number {
  const slice = poseSlice(strip, pose);
  const safe = Number.isFinite(index) ? Math.floor(index) : 0;
  const clamped = Math.min(slice.count - 1, Math.max(0, safe));
  return leftOf((slice.start + clamped) * strip.frameW);
}

/** Avoids `-0`, which is a real value in JS and leaks into CSS and assertions. */
function leftOf(px: number): number {
  return px === 0 ? 0 : -px;
}

export interface StripAnimation {
  /** Frame 0 of the pose. */
  fromPx: number;
  /**
   * One frame PAST the last one. `steps(count)` never renders this position, it
   * is only the end point the timing function divides — the classic sprite walk.
   */
  toPx: number;
  steps: number;
  durationMs: number;
  /** `background-size` width, i.e. the whole strip. */
  widthPx: number;
  frameW: number;
  frameH: number;
  image: string;
}

/**
 * Everything the CSS needs for one pose. Duration comes from the atlas fps, so a
 * 4-frame idle at 6 fps is a 667 ms loop.
 */
export function stripAnimationCss(
  strip: SpriteStrip,
  pose: OmniPose | string,
): StripAnimation {
  const slice = poseSlice(strip, pose);
  const start = slice.start * strip.frameW;
  const fps = slice.fps > 0 ? slice.fps : 1;
  return {
    fromPx: leftOf(start),
    toPx: leftOf(start + slice.count * strip.frameW),
    steps: slice.count,
    durationMs: Math.round((slice.count / fps) * 1000),
    widthPx: strip.frames * strip.frameW,
    frameW: strip.frameW,
    frameH: strip.frameH,
    image: strip.image,
  };
}

// --- drift guard: recompute the descriptor straight from the world atlas -----

interface AtlasFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface AtlasAnim {
  fps: number;
  loop: boolean;
  dirs: Record<string, string[] | { mirror_of: string }>;
}

export interface OmniAtlas {
  pages: string[];
  frames: Record<string, AtlasFrame>;
  anims: Record<string, AtlasAnim>;
}

/**
 * Derives the strip descriptor from a parsed `atlas.json`, exactly as the offline
 * repacker does: the poses are laid out side by side in `STRIP_POSES` order, each
 * taking the frames of `dir` in atlas order. Throws when the art no longer matches
 * the assumption (missing pose, mirrored direction, mixed frame sizes), which is
 * what the test asserts against.
 */
export function stripFromAtlas(
  atlas: OmniAtlas,
  poses: readonly OmniPose[] = STRIP_POSES,
  dir: string = STRIP_DIRECTION,
  image: string = OMNI_STRIP.image,
): SpriteStrip {
  let frameW = 0;
  let frameH = 0;
  let cursor = 0;
  const out: Partial<Record<OmniPose, PoseSlice>> = {};

  for (const pose of poses) {
    const anim = atlas.anims[`omni/${pose}`];
    if (!anim) throw new Error(`atlas has no animation omni/${pose}`);
    const keys = anim.dirs[dir];
    if (!Array.isArray(keys)) {
      throw new Error(`omni/${pose} direction ${dir} is a mirror, not a frame list`);
    }
    for (const key of keys) {
      const frame = atlas.frames[key];
      if (!frame) throw new Error(`atlas has no frame ${key}`);
      if (frameW === 0) {
        frameW = frame.w;
        frameH = frame.h;
      } else if (frame.w !== frameW || frame.h !== frameH) {
        throw new Error(`frame ${key} is ${frame.w}x${frame.h}, expected ${frameW}x${frameH}`);
      }
    }
    out[pose] = { start: cursor, count: keys.length, fps: anim.fps, loop: anim.loop };
    cursor += keys.length;
  }

  return {
    image,
    frameW,
    frameH,
    frames: cursor,
    poses: out as Record<OmniPose, PoseSlice>,
  };
}
